### PR TITLE
Updating Discord icon & moving logo to inline SVG

### PR DESCRIPTION
**Pull request by caburum**

### CODE REVIEW

**Comment by cyfinfaza** [comment]
Remove the inline SVG. Inline SVGs cannot be cached, and greatly increase page load time, as well as code clutter. We should only use inline SVGs when we need to dynamically modify SVG content or styles.

**Comment by caburum** [comment]
It's not that big of a file so I would think having to make an extra request would be slower than just having it inline, but then there's caching so IDK. I think "greatly" is 100% the wrong word though.
I moved the logo back to an external file, and cleaned up duplicate files.

**Comment by cyfinfaza** [comment]
Documentation purposes:
Vercel did not create a preview deployment for this PR. I verified it locally, but we need to get Vercel preview deployments working if we are going to be making changes in this fashion (fork+pr). I think we should just commit to branches of the actual repo, rather than creating forks. We can discuss this at a later meeting.

**Comment by cyfinfaza** [comment]
Apparently Vercel did not update the repo correctly after the transfer, and it is not seeing this merge. I will have to likely take down the site and put it back up, or find some other way to fix that situation. This change will not be live until that issue has been resolved.

**Pull request merged**
